package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"regexp"
	"strings"
	"time"
)

// YTSegment is one timed transcript segment.
type YTSegment struct {
	StartSec    float64 `json:"start_sec"`
	DurationSec float64 `json:"duration_sec,omitempty"`
	Text        string  `json:"text"`
}

// YTCaptionTrack is one available caption language.
type YTCaptionTrack struct {
	LanguageCode string `json:"language_code"`
	LanguageName string `json:"language_name"`
	Kind         string `json:"kind,omitempty"` // "asr" = auto-generated
	Translatable bool   `json:"translatable,omitempty"`
}

// YouTubeTranscriptOutput is the response.
type YouTubeTranscriptOutput struct {
	VideoID          string           `json:"video_id"`
	URL              string           `json:"url"`
	Title            string           `json:"title,omitempty"`
	Channel          string           `json:"channel,omitempty"`
	UploadDate       string           `json:"upload_date,omitempty"`
	DurationSec      int              `json:"duration_seconds,omitempty"`
	ViewCount        int              `json:"view_count,omitempty"`
	Description      string           `json:"description_excerpt,omitempty"`
	AvailableTracks  []YTCaptionTrack `json:"available_caption_tracks,omitempty"`
	SelectedLanguage string           `json:"selected_language,omitempty"`
	IsAutoGenerated  bool             `json:"is_auto_generated,omitempty"`
	Segments         []YTSegment      `json:"segments,omitempty"`
	FullText         string           `json:"full_text,omitempty"`
	WordCount        int              `json:"word_count,omitempty"`
	HighlightFindings []string        `json:"highlight_findings"`
	Source           string           `json:"source"`
	TookMs           int64            `json:"tookMs"`
	Note             string           `json:"note,omitempty"`
}

// raw caption track structure as embedded in YouTube page HTML
type ytCaptionTrackRaw struct {
	BaseURL      string `json:"baseUrl"`
	Name         struct {
		SimpleText string `json:"simpleText"`
		Runs       []struct {
			Text string `json:"text"`
		} `json:"runs"`
	} `json:"name"`
	VSSID         string `json:"vssId"`
	LanguageCode  string `json:"languageCode"`
	Kind          string `json:"kind"`
	IsTranslatable bool  `json:"isTranslatable"`
}

// timedtext json3 format
type ytTimedTextJSON3 struct {
	Events []struct {
		TStartMs int64 `json:"tStartMs"`
		DDurationMs int64 `json:"dDurationMs"`
		Segs     []struct {
			UTF8 string `json:"utf8"`
			TOffsetMs int64 `json:"tOffsetMs,omitempty"`
		} `json:"segs"`
	} `json:"events"`
}

var (
	ytVideoIDRe       = regexp.MustCompile(`(?:v=|youtu\.be/|/embed/|/shorts/)([A-Za-z0-9_-]{11})`)
	ytCaptionTracksRe = regexp.MustCompile(`"captionTracks":(\[.*?\])`)
	ytTitleRe         = regexp.MustCompile(`<meta name="title" content="([^"]+)"`)
	ytChannelRe       = regexp.MustCompile(`"author":"([^"]+)"`)
	ytDurationRe      = regexp.MustCompile(`"lengthSeconds":"([0-9]+)"`)
	ytViewCountRe     = regexp.MustCompile(`"viewCount":"([0-9]+)"`)
	ytUploadDateRe    = regexp.MustCompile(`"uploadDate":"([^"]+)"`)
	ytDescriptionRe   = regexp.MustCompile(`"shortDescription":"((?:[^"\\]|\\.)*)"`)
)

// YouTubeTranscript fetches the transcript for a YouTube video by parsing
// caption tracks embedded in the watch-page HTML and fetching the
// corresponding timedtext JSON. Free, no auth.
//
// Why this matters for ER:
//   - YouTube hosts an enormous corpus of OSINT-relevant content:
//     interviews, conference talks (DefCon, BlackHat, NeurIPS, etc),
//     podcasts (with names mentioned), corporate earnings calls,
//     leaked footage, livestream recordings.
//   - Video content is invisible to text search; transcripts make it
//     queryable. A single 1-hour interview can yield hundreds of named
//     entities + statements that no other source captures.
//   - Use cases: extract names mentioned in a conference talk; verify
//     when a person made a claim publicly; find every YouTube interview
//     that mentions a specific person/company; extract email addresses
//     read aloud (rare but happens with cryptographers/researchers).
//   - Pairs with `firecrawl_extract` for downstream entity extraction
//     from the transcript text.
//
// Input is either a video ID, a watch URL (youtube.com/watch?v=ID), or
// a youtu.be short URL. The tool resolves all three. Optional language
// preference; defaults to English with auto-generated fallback.
func YouTubeTranscript(ctx context.Context, input map[string]any) (*YouTubeTranscriptOutput, error) {
	rawInput, _ := input["video"].(string)
	rawInput = strings.TrimSpace(rawInput)
	if rawInput == "" {
		return nil, fmt.Errorf("input.video required (YouTube video ID, watch URL, or youtu.be URL)")
	}

	languagePref, _ := input["language"].(string)
	languagePref = strings.ToLower(strings.TrimSpace(languagePref))
	if languagePref == "" {
		languagePref = "en"
	}

	includeSegments := true
	if v, ok := input["include_segments"].(bool); ok {
		includeSegments = v
	}

	// Extract video ID
	videoID := ""
	if len(rawInput) == 11 && !strings.Contains(rawInput, "/") && !strings.Contains(rawInput, "=") {
		videoID = rawInput
	} else if m := ytVideoIDRe.FindStringSubmatch(rawInput); len(m) > 1 {
		videoID = m[1]
	}
	if videoID == "" {
		return nil, fmt.Errorf("could not extract video ID from '%s'", rawInput)
	}

	out := &YouTubeTranscriptOutput{
		VideoID: videoID,
		URL:     "https://www.youtube.com/watch?v=" + videoID,
		Source:  "youtube.com (caption tracks embedded in watch-page HTML)",
	}
	start := time.Now()
	client := &http.Client{Timeout: 30 * time.Second}

	// Step 1: fetch watch page
	req, _ := http.NewRequestWithContext(ctx, "GET", out.URL, nil)
	req.Header.Set("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36")
	req.Header.Set("Accept", "text/html,application/xhtml+xml,application/xml")
	req.Header.Set("Accept-Language", "en-US,en;q=0.9")
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("fetch watch page: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("youtube %d", resp.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, 8<<20))
	if err != nil {
		return nil, err
	}
	html := string(body)

	// Step 2: extract metadata
	if m := ytTitleRe.FindStringSubmatch(html); len(m) > 1 {
		out.Title = ytDecodeHTMLEntities(m[1])
	}
	if m := ytChannelRe.FindStringSubmatch(html); len(m) > 1 {
		out.Channel = ytDecodeJSONString(m[1])
	}
	if m := ytDurationRe.FindStringSubmatch(html); len(m) > 1 {
		var n int
		fmt.Sscanf(m[1], "%d", &n)
		out.DurationSec = n
	}
	if m := ytViewCountRe.FindStringSubmatch(html); len(m) > 1 {
		var n int
		fmt.Sscanf(m[1], "%d", &n)
		out.ViewCount = n
	}
	if m := ytUploadDateRe.FindStringSubmatch(html); len(m) > 1 {
		out.UploadDate = m[1]
	}
	if m := ytDescriptionRe.FindStringSubmatch(html); len(m) > 1 {
		desc := ytDecodeJSONString(m[1])
		if len(desc) > 600 {
			desc = desc[:600] + "..."
		}
		out.Description = desc
	}

	// Step 3: extract caption tracks JSON
	m := ytCaptionTracksRe.FindStringSubmatch(html)
	if len(m) < 2 {
		out.Note = "no caption tracks found — video has no subtitles or auto-generated captions disabled"
		out.HighlightFindings = []string{out.Note}
		out.TookMs = time.Since(start).Milliseconds()
		return out, nil
	}
	var tracks []ytCaptionTrackRaw
	if err := json.Unmarshal([]byte(m[1]), &tracks); err != nil {
		return nil, fmt.Errorf("caption tracks decode: %w", err)
	}

	for _, t := range tracks {
		ct := YTCaptionTrack{
			LanguageCode: t.LanguageCode,
			Kind:         t.Kind,
			Translatable: t.IsTranslatable,
		}
		if t.Name.SimpleText != "" {
			ct.LanguageName = t.Name.SimpleText
		} else if len(t.Name.Runs) > 0 {
			ct.LanguageName = t.Name.Runs[0].Text
		}
		out.AvailableTracks = append(out.AvailableTracks, ct)
	}

	// Step 4: choose track by language preference
	var chosen *ytCaptionTrackRaw
	for i := range tracks {
		if strings.HasPrefix(strings.ToLower(tracks[i].LanguageCode), languagePref) {
			chosen = &tracks[i]
			break
		}
	}
	if chosen == nil && len(tracks) > 0 {
		chosen = &tracks[0]
	}
	if chosen == nil {
		out.Note = "caption tracks present but none could be selected"
		out.HighlightFindings = []string{out.Note}
		out.TookMs = time.Since(start).Milliseconds()
		return out, nil
	}
	out.SelectedLanguage = chosen.LanguageCode
	out.IsAutoGenerated = chosen.Kind == "asr"

	// Step 5: fetch transcript via Kome.ai (free no-auth; YouTube's signed
	// captionTracks URL is no longer fetchable outside the player context as
	// of late 2025).
	transcriptText, ktErr := ytFetchKomeTranscript(ctx, client, videoID)
	if ktErr != nil || transcriptText == "" {
		// Fallback: try direct YouTube timedtext fetch (works for some videos)
		timedURL := chosen.BaseURL + "&fmt=json3"
		treq, _ := http.NewRequestWithContext(ctx, "GET", timedURL, nil)
		treq.Header.Set("User-Agent", "Mozilla/5.0 (compatible; osint-agent/0.1)")
		treq.Header.Set("Referer", "https://www.youtube.com/")
		tresp, terr := client.Do(treq)
		if terr == nil {
			defer tresp.Body.Close()
			tbody, _ := io.ReadAll(io.LimitReader(tresp.Body, 16<<20))
			if len(tbody) > 0 {
				var rawTT ytTimedTextJSON3
				if err := json.Unmarshal(tbody, &rawTT); err == nil {
					var fullText strings.Builder
					for _, ev := range rawTT.Events {
						if len(ev.Segs) == 0 {
							continue
						}
						segText := ""
						for _, s := range ev.Segs {
							segText += s.UTF8
						}
						segText = strings.TrimSpace(segText)
						if segText == "" {
							continue
						}
						fullText.WriteString(segText)
						fullText.WriteString(" ")
						if includeSegments {
							out.Segments = append(out.Segments, YTSegment{
								StartSec:    float64(ev.TStartMs) / 1000.0,
								DurationSec: float64(ev.DDurationMs) / 1000.0,
								Text:        segText,
							})
						}
					}
					transcriptText = strings.Join(strings.Fields(fullText.String()), " ")
				}
			}
		}
	}

	if transcriptText == "" {
		out.Note = "transcript fetch failed — both Kome.ai and direct YouTube timedtext returned empty (video may have no captions or YouTube has restricted unauthenticated access)"
		out.HighlightFindings = buildYTTranscriptHighlights(out)
		out.TookMs = time.Since(start).Milliseconds()
		return out, nil
	}

	out.FullText = transcriptText
	out.WordCount = len(strings.Fields(transcriptText))

	out.HighlightFindings = buildYTTranscriptHighlights(out)
	out.TookMs = time.Since(start).Milliseconds()
	return out, nil
}

// ytFetchKomeTranscript uses kome.ai's free public transcript API.
// Returns empty string on any failure.
func ytFetchKomeTranscript(ctx context.Context, client *http.Client, videoID string) (string, error) {
	body := fmt.Sprintf(`{"video_id":"%s","format":true}`, videoID)
	req, _ := http.NewRequestWithContext(ctx, "POST", "https://kome.ai/api/transcript", strings.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("User-Agent", "Mozilla/5.0 (compatible; osint-agent/0.1)")
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("kome.ai %d", resp.StatusCode)
	}
	data, err := io.ReadAll(io.LimitReader(resp.Body, 16<<20))
	if err != nil {
		return "", err
	}
	var parsed struct {
		Transcript string `json:"transcript"`
	}
	if err := json.Unmarshal(data, &parsed); err != nil {
		return "", err
	}
	return strings.Join(strings.Fields(parsed.Transcript), " "), nil
}

func ytDecodeJSONString(s string) string {
	// Decode common JSON escapes that survive the regex
	s = strings.ReplaceAll(s, `\\"`, `"`)
	s = strings.ReplaceAll(s, `\\n`, " ")
	s = strings.ReplaceAll(s, `\n`, " ")
	s = strings.ReplaceAll(s, `\\u0026`, "&")
	s = strings.ReplaceAll(s, `&`, "&")
	s = strings.ReplaceAll(s, `\\/`, "/")
	s = strings.ReplaceAll(s, `\/`, "/")
	return strings.TrimSpace(s)
}

func ytDecodeHTMLEntities(s string) string {
	s = strings.ReplaceAll(s, "&amp;", "&")
	s = strings.ReplaceAll(s, "&lt;", "<")
	s = strings.ReplaceAll(s, "&gt;", ">")
	s = strings.ReplaceAll(s, "&quot;", `"`)
	s = strings.ReplaceAll(s, "&#39;", "'")
	return s
}

func buildYTTranscriptHighlights(o *YouTubeTranscriptOutput) []string {
	hi := []string{}
	hi = append(hi, fmt.Sprintf("✓ %s — %s", o.VideoID, o.Title))
	if o.Channel != "" {
		hi = append(hi, "channel: "+o.Channel)
	}
	if o.UploadDate != "" {
		hi = append(hi, "upload_date: "+o.UploadDate)
	}
	if o.DurationSec > 0 {
		hi = append(hi, fmt.Sprintf("duration: %dm %ds (%d seconds)", o.DurationSec/60, o.DurationSec%60, o.DurationSec))
	}
	if o.ViewCount > 0 {
		hi = append(hi, fmt.Sprintf("view_count: %d", o.ViewCount))
	}
	if len(o.AvailableTracks) > 0 {
		langs := []string{}
		for _, t := range o.AvailableTracks {
			suffix := ""
			if t.Kind == "asr" {
				suffix = " (auto-gen)"
			}
			langs = append(langs, t.LanguageCode+suffix)
		}
		hi = append(hi, fmt.Sprintf("📝 %d caption tracks: %s", len(o.AvailableTracks), strings.Join(langs, ", ")))
	}
	if o.SelectedLanguage != "" {
		gen := ""
		if o.IsAutoGenerated {
			gen = " (auto-generated)"
		}
		hi = append(hi, fmt.Sprintf("🔤 selected: %s%s", o.SelectedLanguage, gen))
	}
	if o.WordCount > 0 {
		hi = append(hi, fmt.Sprintf("📜 transcript: %d words across %d segments", o.WordCount, len(o.Segments)))
	}
	return hi
}
